CHOICES_georefMethod = (
('None', 'None'),
('Publication', 'Publication'),
('GetLatLon.com', 'GetLatLon.com'),
('GoogleEarth', 'GoogleEarth'),
)

CHOICES_AfricanCountry = (
("Algeria", "Algeria"),
("Angola", "Angola"),
("Benin", "Benin"),
("Botswana", "Botswana"),
("Burkina Faso", "Burkina Faso"),
("Burundi", "Burundi"),
("Cameroon", "Cameroon"),
("Cape Verde", "Cape Verde"),
("Central African Republic", "Central African Republic"),
("Chad", "Chad"),
("Congo, Democratic Republic of", "Congo, Democratic Republic of"),
("Cote dIvoire (Ivory Coast),", "Cote dIvoire (Ivory Coast),"),
("Djibouti", "Djibouti"),
("Egypt", "Egypt"),
("Equatorial Guinea", "Equatorial Guinea"),
("Eritrea", "Eritrea"),
("Ethiopia", "Ethiopia"),
("Gabon", "Gabon"),
("Gambia", "Gambia"),
("Ghana", "Ghana"),
("Guinea", "Guinea"),
("Guinea-Bissau", "Guinea-Bissau"),
("Kenya", "Kenya"),
("Lesotho", "Lesotho"),
("Liberia", "Liberia"),
("Libya", "Libya"),
("Madagascar", "Madagascar"),
("Malawi", "Malawi"),
("Mali", "Mali"),
("Mauritania", "Mauritania"),
("Mauritius", "Mauritius"),
("Morocco", "Morocco"),
("Mozambique", "Mozambique"),
("Namibia", "Namibia"),
("Niger", "Niger"),
("Nigeria", "Nigeria"),
("Rwanda", "Rwanda"),
("Sao Tome and Principe", "Sao Tome and Principe"),
("Senegal", "Senegal"),
("Seychelles", "Seychelles"),
("Sierra Leone", "Sierra Leone"),
("Somalia", "Somalia"),
("South Africa", "South Africa"),
("South Sudan", "South Sudan"),
("Sudan", "Sudan"),
("Swaziland", "Swaziland"),
("Tanzania", "Tanzania"),
("Togo", "Togo"),
("Tunisia", "Tunisia"),
("Western Sahara", "Western Sahara"),
("Uganda", "Uganda"),
("Zambia", "Zambia"),
("Zimbabwe", "Zimbabwe"),
)