CHOICES_georefMethod = (
('None', 'None'),
('Publication', 'Publication'),
('GetLatLon.com', 'GetLatLon.com'),
('GoogleEarth', 'GoogleEarth'),
)

CHOICES_AfricanCountry = (
("Algeria", "Algeria"),
("Angola", "Angola"),
("Benin", "Benin"),
("Botswana", "Botswana"),
("Burkina Faso", "Burkina Faso"),
("Burundi", "Burundi"),
("Cameroon", "Cameroon"),
("Cape Verde", "Cape Verde"),
("Central African Republic", "Central African Republic"),
("Chad", "Chad"),
("Congo, Democratic Republic of", "Congo, Democratic Republic of"),
("Cote dIvoire (Ivory Coast),", "Cote dIvoire (Ivory Coast),"),
("Djibouti", "Djibouti"),
("Egypt", "Egypt"),
("Equatorial Guinea", "Equatorial Guinea"),
("Eritrea", "Eritrea"),
("Ethiopia", "Ethiopia"),
("Gabon", "Gabon"),
("Gambia", "Gambia"),
("Ghana", "Ghana"),
("Guinea", "Guinea"),
("Guinea-Bissau", "Guinea-Bissau"),
("Kenya", "Kenya"),
("Lesotho", "Lesotho"),
("Liberia", "Liberia"),
("Libya", "Libya"),
("Madagascar", "Madagascar"),
("Malawi", "Malawi"),
("Mali", "Mali"),
("Mauritania", "Mauritania"),
("Mauritius", "Mauritius"),
("Morocco", "Morocco"),
("Mozambique", "Mozambique"),
("Namibia", "Namibia"),
("Niger", "Niger"),
("Nigeria", "Nigeria"),
("Rwanda", "Rwanda"),
("Sao Tome and Principe", "Sao Tome and Principe"),
("Senegal", "Senegal"),
("Seychelles", "Seychelles"),
("Sierra Leone", "Sierra Leone"),
("Somalia", "Somalia"),
("South Africa", "South Africa"),
("South Sudan", "South Sudan"),
("Sudan", "Sudan"),
("Swaziland", "Swaziland"),
("Tanzania", "Tanzania"),
("Togo", "Togo"),
("Tunisia", "Tunisia"),
("Western Sahara", "Western Sahara"),
("Uganda", "Uganda"),
("Zambia", "Zambia"),
("Zimbabwe", "Zimbabwe"),
)

CHOICES_Americas_plusAustralia=(
('Anguilla','Anguilla'),
('Antigua and Barbuda','Antigua and Barbuda'),
('Argentina','Argentina'),
('Aruba','Aruba'),
('Australia','Australia'),
('Bahamas','Bahamas'),
('Barbados','Barbados'),
('Belize','Belize'),
('Bermuda','Bermuda'),
('Bolivia','Bolivia'),
('Brazil','Brazil'),
('British Virgin Islands','British Virgin Islands'),
('Canada','Canada'),
('Cayman Islands','Cayman Islands'),
('Chile','Chile'),
('Colombia','Colombia'),
('Costa Rica','Costa Rica'),
('Cuba','Cuba'),
('Dominica','Dominica'),
('Dominican Republic','Dominican Republic'),
('Ecuador','Ecuador'),
('El Salvador','El Salvador'),
('French Guiana','French Guiana'),
('Grenada','Grenada'),
('Guadeloupe','Guadeloupe'),
('Guatemala','Guatemala'),
('Guyana','Guyana'),
('Haiti','Haiti'),
('Honduras','Honduras'),
('Jamaica','Jamaica'),
('Martinique','Martinique'),
('Mexico','Mexico'),
('Montserrat','Montserrat'),
('Netherlands Antilles','Netherlands Antilles'),
('Nicaragua','Nicaragua'),
('Panama','Panama'),
('Paraguay','Paraguay'),
('Peru','Peru'),
('Puerto Rico','Puerto Rico'),
('Saint Kitts and Nevis','Saint Kitts and Nevis'),
('Saint Lucia','Saint Lucia'),
('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines'),
('Suriname','Suriname'),
('Trinidad and Tobago','Trinidad and Tobago'),
('United States','United States'),
('Uruguay','Uruguay'),
('US Virgin Islands','US Virgin Islands'),
('Venezuela','Venezuela')
)

CHOICES_Asian_country = (
('Afghanistan','Afghanistan'),
('Armenia','Armenia'),
('Azerbaijan','Azerbaijan'),
('Bahrain','Bahrain'),
('Bangladesh','Bangladesh'),
('Bhutan','Bhutan'),
('Brunei','Brunei'),
('Myanmar','Myanmar'),
('Cambodia','Cambodia'),
('China','China'),
('India','India'),
('Indonesia','Indonesia'),
('Iran','Iran'),
('Iraq','Iraq'),
('Israel','Israel'),
('Japan','Japan'),
('Jordan','Jordan'),
('Kazakhstan','Kazakhstan'),
('North Korea','North Korea'),
('South Korea','South Korea'),
('Kuwait','Kuwait'),
('Kyrgyzstan','Kyrgyzstan'),
('Laos','Laos'),
('Lebanon','Lebanon'),
('Malaysia','Malaysia'),
('Maldives','Maldives'),
('Mongolia','Mongolia'),
('Nepal','Nepal'),
('Oman','Oman'),
('Pakistan','Pakistan'),
('Philippines','Philippines'),
('Qatar','Qatar'),
('Saudi Arabia','Saudi Arabia'),
('Singapore','Singapore'),
('Sri Lanka','Sri Lanka'),
('Syria','Syria'),
('Taiwan','Taiwan'),
('Tajikistan','Tajikistan'),
('Thailand','Thailand'),
('Timor-Leste','Timor-Leste'),
('Turkmenistan','Turkmenistan'),
('United Arab Emirates','United Arab Emirates'),
('Uzbekistan','Uzbekistan'),
('Vietnam','Vietnam'),
('Yemen','Yemen')
)

CHOICES_ALL_COUNTRIES=(
("Afghanistan","Afghanistan"),
("Algeria", "Algeria"),
("Angola", "Angola"),
("Anguilla","Anguilla"),
("Antigua and Barbuda","Antigua and Barbuda"),
("Argentina","Argentina"),
("Armenia","Armenia"),
("Aruba","Aruba"),
("Australia","Australia"),
("Azerbaijan","Azerbaijan"),
("Bahamas","Bahamas"),
("Bahrain","Bahrain"),
("Bangladesh","Bangladesh"),
("Barbados","Barbados"),
("Belize","Belize"),
("Benin", "Benin"),
("Bermuda","Bermuda"),
("Bhutan","Bhutan"),
("Bolivia","Bolivia"),
("Botswana", "Botswana"),
("Brazil","Brazil"),
("British Virgin Islands","British Virgin Islands"),
("Brunei","Brunei"),
("Burkina Faso", "Burkina Faso"),
("Burundi", "Burundi"),
("Cambodia","Cambodia"),
("Cameroon", "Cameroon"),
("Canada","Canada"),
("Cape Verde", "Cape Verde"),
("Cayman Islands","Cayman Islands"),
("Central African Republic", "Central African Republic"),
("Chad", "Chad"),
("Chile","Chile"),
("China","China"),
("Colombia","Colombia"),
("Congo, Democratic Republic of", "Congo, Democratic Republic of"),
("Costa Rica","Costa Rica"),
("Cote dIvoire (Ivory Coast),", "Cote dIvoire (Ivory Coast),"),
("Cuba","Cuba"),
("Djibouti", "Djibouti"),
("Dominica","Dominica"),
("Dominican Republic","Dominican Republic"),
("Ecuador","Ecuador"),
("Egypt", "Egypt"),
("El Salvador","El Salvador"),
("Equatorial Guinea", "Equatorial Guinea"),
("Eritrea", "Eritrea"),
("Ethiopia", "Ethiopia"),
("French Guiana","French Guiana"),
("Gabon", "Gabon"),
("Gambia", "Gambia"),
("Ghana", "Ghana"),
("Grenada","Grenada"),
("Guadeloupe","Guadeloupe"),
("Guatemala","Guatemala"),
("Guinea-Bissau", "Guinea-Bissau"),
("Guinea", "Guinea"),
("Guyana","Guyana"),
("Haiti","Haiti"),
("Honduras","Honduras"),
("India","India"),
("Indonesia","Indonesia"),
("Iran","Iran"),
("Iraq","Iraq"),
("Israel","Israel"),
("Jamaica","Jamaica"),
("Japan","Japan"),
("Jordan","Jordan"),
("Kazakhstan","Kazakhstan"),
("Kenya", "Kenya"),
("Kuwait","Kuwait"),
("Kyrgyzstan","Kyrgyzstan"),
("Laos","Laos"),
("Lebanon","Lebanon"),
("Lesotho", "Lesotho"),
("Liberia", "Liberia"),
("Libya", "Libya"),
("Madagascar", "Madagascar"),
("Malawi", "Malawi"),
("Malaysia","Malaysia"),
("Maldives","Maldives"),
("Mali", "Mali"),
("Martinique","Martinique"),
("Mauritania", "Mauritania"),
("Mauritius", "Mauritius"),
("Mexico","Mexico"),
("Mongolia","Mongolia"),
("Montserrat","Montserrat"),
("Morocco", "Morocco"),
("Mozambique", "Mozambique"),
("Myanmar","Myanmar"),
("Namibia", "Namibia"),
("Nepal","Nepal"),
("Netherlands Antilles","Netherlands Antilles"),
("Nicaragua","Nicaragua"),
("Niger", "Niger"),
("Nigeria", "Nigeria"),
("North Korea","North Korea"),
("Oman","Oman"),
("Pakistan","Pakistan"),
("Panama","Panama"),
("Paraguay","Paraguay"),
("Peru","Peru"),
("Philippines","Philippines"),
("Puerto Rico","Puerto Rico"),
("Qatar","Qatar"),
("Rwanda", "Rwanda"),
("Saint Kitts and Nevis","Saint Kitts and Nevis"),
("Saint Lucia","Saint Lucia"),
("Saint Vincent and the Grenadines","Saint Vincent and the Grenadines"),
("Sao Tome and Principe", "Sao Tome and Principe"),
("Saudi Arabia","Saudi Arabia"),
("Senegal", "Senegal"),
("Seychelles", "Seychelles"),
("Sierra Leone", "Sierra Leone"),
("Singapore","Singapore"),
("Somalia", "Somalia"),
("South Africa", "South Africa"),
("South Korea","South Korea"),
("South Sudan", "South Sudan"),
("Sri Lanka","Sri Lanka"),
("Sudan", "Sudan"),
("Suriname","Suriname"),
("Swaziland", "Swaziland"),
("Syria","Syria"),
("Taiwan","Taiwan"),
("Tajikistan","Tajikistan"),
("Tanzania", "Tanzania"),
("Thailand","Thailand"),
("Timor-Leste","Timor-Leste"),
("Togo", "Togo"),
("Trinidad and Tobago","Trinidad and Tobago"),
("Tunisia", "Tunisia"),
("Turkmenistan","Turkmenistan"),
("Uganda", "Uganda"),
("United Arab Emirates","United Arab Emirates"),
("United States","United States"),
("Uruguay","Uruguay"),
("US Virgin Islands","US Virgin Islands"),
("Uzbekistan","Uzbekistan"),
("Venezuela","Venezuela"),
("Vietnam","Vietnam"),
("Western Sahara", "Western Sahara"),
("Yemen","Yemen"),
("Zambia", "Zambia"),
("Zimbabwe", "Zimbabwe"),
)